### PR TITLE
Try fixing i386 & arm builds

### PR DESCRIPTION
**Pull request by coslyk**
I can't find out why JSC_HOST_CALL is not set correctly, so I use a script to replace them with the correct one. It's not a good solution, but should work.

Adding `-DENABLE_ALLINONE_BUILD=OFF` may reduce the memory use when linking in ARM.

### CODE REVIEW

**Comment by coslyk** [comment]
Now the new patch fixes the compilation error, but new error occurs in linking due to the lack of memory

```
[4286/4422] Linking CXX shared library lib/libQt5WebKit.so.5.212.0
FAILED: lib/libQt5WebKit.so.5.212.0 
: && /usr/bin/c++ -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -march=i686 -mtune=generic -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-exceptions -fno-strict-aliasing -fno-rtti -std=c++11 -Wno-expansion-to-defined -O3 -DNDEBUG -ffunction-sections -fdata-sections  -Wl,--no-undefined -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed -fuse-ld=gold -Wl,--disable-new-dtags -fuse-ld=gold -Wl,--disable-new-dtags  -Wl,--gc-sections -shared -Wl,-soname,libQt5WebKit.so.5 -o lib/libQt5WebKit.so.5.212.0 Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageAreaImpl.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageAreaSync.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageNamespaceImpl.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageSyncManager.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageThread.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/StorageTracker.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/WebDatabaseProvider.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/Storage/WebStorageNamespaceProvider.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/WebCoreSupport/WebResourceLoadScheduler.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qhttpheader.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebdatabase.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebelement.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebfullscreenrequest.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebhistory.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebhistoryinterface.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebkitglobal.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebplugindatabase.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebpluginfactory.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebscriptworld.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebsecurityorigin.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Api/qwebsettings.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/ChromeClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/ContextMenuClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/DragClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/EditorClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/FrameLoaderClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/FrameNetworkingContextQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/HistorySerialization.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/IconDatabaseClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/InitWebCoreQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/InspectorClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/InspectorServerQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/NotificationPresenterClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/PlatformStrategiesQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/PopupMenuQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/ProgressTrackerClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QWebFrameAdapter.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QWebFrameData.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QWebPageAdapter.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QtPlatformPlugin.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QtPluginWidgetAdapter.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/QtPrintContext.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/SearchPopupMenuQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/TextCheckerClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/TextureMapperLayerClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/UndoStepQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/VisitedLinkStoreQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/WebDatabaseProviderQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/WebEventConversion.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginDatabase.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginDebug.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginPackage.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginStream.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginView.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/GeolocationClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/WebCoreSupport/GeolocationPermissionClientQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/PluginMainThreadScheduler.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/win/Plugins/npapi.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Plugins/PluginPackageQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qt/Plugins/PluginViewQt.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/qrc_WebCore.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/__/__/DerivedSources/WebInspectorUI/qrc_WebInspector.cpp.o Source/WebKit/CMakeFiles/WebKit.dir/WebKit_autogen/mocs_compilation.cpp.o  lib/libJavaScriptCore.a lib/libWTF.a lib/libWebCore.a -Wl,--whole-archive lib/libWebKit2.a -Wl,--no-whole-archive /usr/lib/i386-linux-gnu/libQt5Quick.so.5.12.2 /usr/lib/i386-linux-gnu/libQt5WebChannel.so.5.12.2 -licuuc /usr/lib/i386-linux-gnu/libQt5Positioning.so.5.12.2 -lX11 -lXcomposite -lXrender lib/libWebCore.a lib/libJavaScriptCore.a lib/libWTF.a -licui18n lib/libbmalloc.a -ldl -lpthread lib/libwoff2.a lib/libbrotli.a /usr/lib/i386-linux-gnu/libQt5Sensors.so.5.12.2 -ljpeg -lpng -lz -lwebp -lhyphen -lxml2 -lxslt -lsqlite3 -lgio-2.0 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgstpbutils-1.0 -lgstaudio-1.0 -lgsttag-1.0 -lgstvideo-1.0 -lgstfft-1.0 -ljpeg -lpng -lz -lwebp -lhyphen -lxml2 -lxslt -lsqlite3 -lgio-2.0 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgstpbutils-1.0 -lgstaudio-1.0 -lgsttag-1.0 -lgstvideo-1.0 -lgstfft-1.0 -licuuc -lgobject-2.0 -lglib-2.0 lib/libANGLESupport.a /usr/lib/i386-linux-gnu/libQt5Gui.so.5.12.2 /usr/lib/i386-linux-gnu/libQt5Qml.so.5.12.2 /usr/lib/i386-linux-gnu/libQt5Network.so.5.12.2 /usr/lib/i386-linux-gnu/libQt5Core.so.5.12.2 -lrt -lX11 && :
/usr/lib/gcc/i686-unknown-linux-gnu/8.2.0/../../../../i686-unknown-linux-gnu/bin/ld.gold: fatal error: lib/libQt5WebKit.so.5.212.0: mmap: failed to allocate 2806246084 bytes for output file: Cannot allocate memory
collect2: error: ld returned 1 exit status
```

**Comment by coslyk** [comment]
Maybe disabling Gold linker helps?

**Comment by coslyk** [comment]
It seems that disabling gold linker does not help...
https://flathub.org/builds/#/builders/32/builds/1557
It is the problem with build environments. GCC 8.2 needs larger memory for linking.

**Comment by JBBgameich** [comment]
Maybe https://salsa.debian.org/qt-kde-team/qt/qtwebkit/blob/master/debian/patches/reduce_memory_usage.patch used by debian can help to reduce the required memory.

**Comment by hfiguiere** [comment]
we can close this as WONTFIX. Neither platform is supported anymore

**Pull request closed without merging**
