### PR TITLE
Update runtime to 5.15-21.08

### LINKED ISSUE #25: Runtime 5.15-21.08
We need a 5.15-21.08 branch.

### PR DESCRIPTION
**Pull request by hfiguiere**
Let's get the builder to build. I fixed the early build failure.

The branch will need to be created (I can do it)

Closes #25

### CODE REVIEW

**Comment by hfiguiere** [comment]
Failure because `TRUE` and `FALSE` aren't defined there.

**Comment by hfiguiere** [comment]
Fatal warning with yacc causing the grammar source file to not be generated.

**Comment by hfiguiere** [comment]
@TingPing @barthalion ok to create the branch?

**Comment by TingPing** [comment]
Go for it

**Comment by hfiguiere** [comment]
done. Thanks!

**Pull request closed without merging**
