### PR TITLE
Switch to YAML

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by eszlari** [comment]
Could you create a branch 5.9 after this is merged?

see: https://github.com/flathub/flathub/pull/578

**Comment by barthalion** [comment]
What does it actually bring besides language change and longer download times due to git usage?

**Comment by barthalion** [comment]
Interesting, removing branch closes pull requests…

**Comment by eszlari** [comment]
> What does it actually bring besides language change and longer download times due to git usage?

Just see the git log. There have been commits since the tarball was created.

**Pull request closed without merging**
